name: Scraper CI/CD

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  run-scraper:
    name: Run Web Scraper
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install beautifulsoup4==4.13.4 lxml==5.4.0 requests==2.32.3

      - name: Run scraper with output
        run: |
          echo "Starting scraper..."
          cd lab_5_scraper
          python scraper.py
          echo "Scraper finished with exit code $?"

      - name: Archive results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: scraper-results
          path: lab_5_scraper/tmp/articles